### ISSUE TITLE
Exception Info: System.DllNotFoundException: Unable to load DLL 'Everything.dll'

### ISSUE THREAD

**Issue by babakmdi** [stax76/Everything.NET#5]

**Comment by stax76** [comment]
https://github.com/stax76/Everything.NET#requirements

**Comment by babakmdi** [comment]
should i download exe file ?

**Comment by stax76** [comment]
A requirement is something you need.

https://www.voidtools.com/Everything-1.4.1.1015.x64-Setup.exe

**Comment by babakmdi** [comment]
That is the program itself!
Search can be done with this program!
